### ISSUE TITLE
Feature: `elm.json` (directories) as an answer

### ISSUE THREAD

**Issue by lue-bird** [MartinSStewart/state-of-elm#4]
Feature: Allow submitting `elm.json` file content as an answer to questions like
- "What `elm-review` rules do you use" or
- "What packages do you use generally (or in your current project?)"

In practice, this could mean only accepting the `dependencies` json object (to hide project names).
For some questions, it might also be nice to accept multiple `elm.json` configs.

**Comment by MartinSStewart** [comment]
Closing this as it's included in the 2023 survey (though it's intended for the app elm.json and not the elm-review elm.json so it won't answer the question of which elm-review rules are used)
